- id: ai-review
  name: Review your code with AI
  description: This hook performs a review of your code using an AI model.
  entry: ai-review
  language: python
  types: [python]
  stages: [pre-commit, pre-merge-commit, manual]
  pass_filenames: false
  