name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      # Run tests and check coverage
      - name: Run tests with coverage
        run: |
          coverage run -m pytest .
          coverage report -m --fail-under=90

      # Validate typing with mypy
      - name: Validate typing with mypy
        run: |
          mypy .

      # Validate linter with ruff
      - name: Validate format with ruff
        run: |
          ruff check .

      # Validate format with ruff
      - name: Validate linter with ruff
        run: |
          ruff format . --check
